//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErgoHealthCue.Resources {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErgoHealthCue.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture);
        public static string Settings => ResourceManager.GetString("Settings", resourceCulture);
        public static string Statistics => ResourceManager.GetString("Statistics", resourceCulture);
        public static string ProgressStatistics => ResourceManager.GetString("ProgressStatistics", resourceCulture);
        public static string Exit => ResourceManager.GetString("Exit", resourceCulture);
        public static string TriggerCueNow => ResourceManager.GetString("TriggerCueNow", resourceCulture);
        
        // Settings window
        public static string SettingsTitle => ResourceManager.GetString("SettingsTitle", resourceCulture);
        public static string SettingsSubtitle => ResourceManager.GetString("SettingsSubtitle", resourceCulture);
        public static string ExerciseIntervals => ResourceManager.GetString("ExerciseIntervals", resourceCulture);
        public static string UseRandomIntervals => ResourceManager.GetString("UseRandomIntervals", resourceCulture);
        public static string MinimumInterval => ResourceManager.GetString("MinimumInterval", resourceCulture);
        public static string MaximumInterval => ResourceManager.GetString("MaximumInterval", resourceCulture);
        public static string PositionChangeIntervals => ResourceManager.GetString("PositionChangeIntervals", resourceCulture);
        public static string UseRandomPositionIntervals => ResourceManager.GetString("UseRandomPositionIntervals", resourceCulture);
        public static string StartWithWindows => ResourceManager.GetString("StartWithWindows", resourceCulture);
        public static string AvailablePositions => ResourceManager.GetString("AvailablePositions", resourceCulture);
        public static string AvailablePositionsDesc => ResourceManager.GetString("AvailablePositionsDesc", resourceCulture);
        public static string StandingPosition => ResourceManager.GetString("StandingPosition", resourceCulture);
        public static string SittingPosition => ResourceManager.GetString("SittingPosition", resourceCulture);
        public static string FloorPosition => ResourceManager.GetString("FloorPosition", resourceCulture);
        public static string ManageCuesByPosition => ResourceManager.GetString("ManageCuesByPosition", resourceCulture);
        public static string SelectPositionDesc => ResourceManager.GetString("SelectPositionDesc", resourceCulture);
        public static string Standing => ResourceManager.GetString("Standing", resourceCulture);
        public static string Sitting => ResourceManager.GetString("Sitting", resourceCulture);
        public static string Floor => ResourceManager.GetString("Floor", resourceCulture);
        public static string PositionChanges => ResourceManager.GetString("PositionChanges", resourceCulture);
        public static string Cues => ResourceManager.GetString("Cues", resourceCulture);
        public static string AddNewCue => ResourceManager.GetString("AddNewCue", resourceCulture);
        public static string RemoveSelected => ResourceManager.GetString("RemoveSelected", resourceCulture);
        public static string ViewStatistics => ResourceManager.GetString("ViewStatistics", resourceCulture);
        public static string SaveChanges => ResourceManager.GetString("SaveChanges", resourceCulture);
        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture);
        public static string Showing => ResourceManager.GetString("Showing", resourceCulture);
        
        // Statistics window
        public static string StatisticsTitle => ResourceManager.GetString("StatisticsTitle", resourceCulture);
        public static string StatisticsSubtitle => ResourceManager.GetString("StatisticsSubtitle", resourceCulture);
        public static string TimePeriod => ResourceManager.GetString("TimePeriod", resourceCulture);
        public static string Today => ResourceManager.GetString("Today", resourceCulture);
        public static string ThisWeek => ResourceManager.GetString("ThisWeek", resourceCulture);
        public static string ThisMonth => ResourceManager.GetString("ThisMonth", resourceCulture);
        public static string ThisYear => ResourceManager.GetString("ThisYear", resourceCulture);
        public static string AllTime => ResourceManager.GetString("AllTime", resourceCulture);
        public static string TotalCues => ResourceManager.GetString("TotalCues", resourceCulture);
        public static string Completed => ResourceManager.GetString("Completed", resourceCulture);
        public static string Dismissed => ResourceManager.GetString("Dismissed", resourceCulture);
        public static string History => ResourceManager.GetString("History", resourceCulture);
        public static string Close => ResourceManager.GetString("Close", resourceCulture);
        
        // Cue overlay
        public static string Complete => ResourceManager.GetString("Complete", resourceCulture);
        public static string Dismiss => ResourceManager.GetString("Dismiss", resourceCulture);
        
        // Column headers
        public static string Enabled => ResourceManager.GetString("Enabled", resourceCulture);
        public static string Type => ResourceManager.GetString("Type", resourceCulture);
        public static string Title => ResourceManager.GetString("Title", resourceCulture);
        public static string Description => ResourceManager.GetString("Description", resourceCulture);
        public static string DateTime => ResourceManager.GetString("DateTime", resourceCulture);
        public static string Status => ResourceManager.GetString("Status", resourceCulture);
        public static string ResponseTime => ResourceManager.GetString("ResponseTime", resourceCulture);
    }
}
